///////////////////////////////////////////////////////////
//  DBHelper.cs
//  Implementation of the Class DBHelper
//  Generated by Enterprise Architect
//  Created on:      12-Kas-2022 10:58:47
//  Original author: aykut
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace DAL
{
	public abstract class DBHelper : IDBHelper
	{

		protected string connectionString;

		public string ConnectionString
		{
			get { return connectionString; }
			set { connectionString = value; }
		}

		public DBHelper()
		{

		}

		~DBHelper()
		{

		}

		public abstract void Connect();

		public abstract void Disconnect();

		/// 
		/// <param name="commandText">sql komut içeriði</param>
		public abstract void Run(string commandText);
		

	}
}