///////////////////////////////////////////////////////////
//  IDBHelper.cs
//  Implementation of the Interface IDBHelper
//  Generated by Enterprise Architect
//  Created on:      12-Kas-2022 10:58:50
//  Original author: aykut
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DAL {
	/// <summary>
	/// Bu arayüz db'den baðýmsýz olacak soyut sýnýf arayüzüdür
	/// </summary>
	public interface IDBHelper  {

		void Connect();

		void Disconnect();

		/// 
		/// <param name="commandText">sql komut içeriði</param>
		void Run(string commandText);
	}

}